DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS mpa CASCADE;
DROP TABLE IF EXISTS film CASCADE;
DROP TABLE IF EXISTS genre CASCADE;
DROP TABLE IF EXISTS like_film CASCADE;
DROP TABLE IF EXISTS friend_users CASCADE;
DROP TABLE IF EXISTS film_genre CASCADE;

CREATE TABLE IF NOT EXISTS users (
	id_users Integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email varchar NOT NULL ,
	login varchar NOT NULL ,
	name_user varchar,
	birthday date NOT NULL 
);

CREATE TABLE IF NOT EXISTS mpa (
	id_mpa Integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name_mpa varchar NOT NULL 
);

CREATE TABLE IF NOT EXISTS film (
	id_film Integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name_film varchar NOT NULL,
	description varchar NOT NULL,
	release_date date NOT NULL,
	duration Integer NOT NULL,
	rating_mpa integer REFERENCES mpa (id_mpa) ON DELETE CASCADE/*,
	rate integer*/
);

CREATE TABLE IF NOT EXISTS genre (
	id_genre Integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name_genre varchar NOT NULL
); 

CREATE TABLE IF NOT EXISTS like_film (
 	id_film integer REFERENCES film (id_film) ON DELETE CASCADE,
 	id_users integer REFERENCES users (id_users) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS friend_users (
	id_person integer REFERENCES users (id_users) ON DELETE CASCADE,
	id_friend integer REFERENCES users (id_users) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS film_genre (
	id_film integer REFERENCES film (id_film) ON DELETE CASCADE,
	id_genre integer REFERENCES genre (id_genre) ON DELETE CASCADE
);