INSERT INTO FILM (NAME_FILM, DESCRIPTION, RELEASE_DATE, DURATION, RATING_MPA)
VALUES ('test1', 'testestestestsetsetset', '2020-10-10', 300, 4);

INSERT INTO FILM_GENRE (ID_FILM, ID_GENRE)
VALUES (1, 2);

INSERT INTO FILM_GENRE (ID_FILM, ID_GENRE)
VALUES (1, 1);

INSERT INTO USERS (EMAIL, LOGIN, NAME_USER, BIRTHDAY)
VALUES ('asdasd@mail.ru', 'Loqw', 'Sergei', '1999-10-09');

INSERT INTO USERS (EMAIL, LOGIN, NAME_USER, BIRTHDAY)
VALUES ('vv@mail.ru', 'vv', 'no name', '1989-01-01');

INSERT INTO USERS (EMAIL, LOGIN, NAME_USER, BIRTHDAY)
VALUES ('vasdgfcv@mail.ru', 'fddv', 'name', '1969-11-01');

INSERT INTO USERS (EMAIL, LOGIN, NAME_USER, BIRTHDAY)
VALUES ('vcccccccv@mail.ru', 'cc', 'cc', '1922-12-21');

INSERT INTO FRIEND_USERS (ID_PERSON, ID_FRIEND)
VALUES ('1', '3');

INSERT INTO FRIEND_USERS (ID_PERSON, ID_FRIEND)
VALUES ('4', '3');

SELECT * FROM FRIEND_USERS
WHERE ID_PERSON = 1;

SELECT * FROM FRIEND_USERS
WHERE ID_PERSON = 4;

INSERT INTO LIKE_FILM (ID_FILM, ID_USERS)
VALUES (1, 1);

UPDATE film SET RATE = 1 WHERE ID_FILM = 1;

/*SELECT * FROM FILM;*/

INSERT INTO LIKE_FILM (ID_FILM, ID_USERS)
VALUES (1, 2);

UPDATE film SET RATE = 2 WHERE ID_FILM = 1;
	
/*SELECT * FROM FILM WHERE ID_FILM = 1 ;*/

SELECT * FROM FILM;

SELECT * FROM FILM_GENRE;

SELECT f.*,
		m.name_mpa/*,
		g.name_genre*/
FROM film AS f INNER JOIN mpa AS m ON f.rating_mpa = m.id_mpa;
				/*INNER JOIN FILM_GENRE AS fg ON fg.ID_FILM = f.ID_FILM;
				/*INNER JOIN genre AS g ON g.ID_GENRE = fg.ID_GE

